farm/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('palm/', include("palm.urls")),
]

palm/urls.py
# paml/urls.py
from django.urls import path, re_path
from . import views
app_name = 'palm'
urlpatterns = [

    # index
    # index end

    # control
    path('cctv/', views.cctv, name = 'cctv'),
    path('cctv/<int:id>/', views.cctv_n_house, name = 'cctv_house'),
    path("cctv/control/", views.control, name = "control"),
    path('cctv/control/<int:id>', views.control_n, name = 'control_house'),
    path('cctv/control/temp', views.control_temp, name='control_temp'),
    # 이 url은 아마 데이터 통신을 담당할 것 즉 리다이렉트 되는 url 주소가 된다 (명령어처리)
    # control end

    # setting
    path('setting/', views.setting, name = 'setting'),
    path('setting/<int:id>/', views.setting_n, name = 'setting_house'),
    path('setting/<int:id>/emergency/', views.emergency, name = 'emergency'),
    path('setting/<int:id>/operating/', views.operating, name = 'operating'),
    path('setting/<int:id>/emergency/edit', views.emergency_edit, name = 'emergency_edit'),
    # edit을 하기위해선 그 테이블에 user와 gcg_id의 외래키를 가진 row가 존재해야한다 따라서 user을 등록하는 과정에서 이를 같이 등록하는것이 유연할거같음
    # 더정확히 묘사하자면 user 을 등록할때 새로운 row를 만들어주는데 외래키는 user와 gcg_id의 외래키를 가지고, value는 default(쉽게 수정이가능한 값) 으로 설정해둠(동적으로)
    path('setting/<int:gcg_id>/operating/<int:opr_id>/edit/', views.operating_edit, name = 'operating_edit'),
    path('setting/temp', views.setting_temp, name = 'temp'),
    # 마찬가지로 데이터 통신을 담당하는 url(리다이렉트시킬)
    # setting end

    # record
    path('vegi/', views.vegi_category, name = 'vegi_category'),
    path('vegi/<int:vegi_id>/', views.record_list, name = 'record_list'),
    path('vegi/<int:vegi_id>/<int:record_id>/', views.record_detail, name = 'record_detail'),
    # record/record_vegi_new
    path('vegi/new/', views.vegi_category_new, name = 'record_vegi_new'),
    # record/record_vegi_record_new
    path('vegi/<int:vegi_id>/new/', views.record_new, name = 'record_new'),
    path('vegi/<int:vegi_id>/<int:record_id>/edit/', views.record_edit, name = 'record_edit'),
    # record_end
    path('test/', views.test, name = 'test'),
    path('test_display/', views.test_display, name = 'test_display'),
    # path('test/<str:response>/', views.test_response, name = 'test_response'),
    path('test/<int:anode_id>/', views.request_to_GCG, name = 'request_GCG'),
    # test url

]

palm/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
import datetime, time

class Owner(models.Model):
    name = models.CharField(max_length=100)
    address = models.ForeignKey('Address', on_delete=models.PROTECT)
    house_num = models.IntegerField()
    joined_at = models.DateTimeField(auto_now_add = True)
    pass
class CctvOutside(models.Model):
    gcg = models.ForeignKey('Gcg', on_delete=models.CASCADE)
    value = models.CharField(max_length=50)
    def __str__(self):
        return 'cctv_outside of {}'.format(self.gcg)
# cctv 외부와 내부를 나누어 각각의 URL 혹은 IP주소를 저장한다. 이렇게 하는게 GCG 에서 접근하기가 편하게 할수있다.
class CctvInside(models.Model):
    gcg = models.ForeignKey('Gcg', on_delete=models.CASCADE)
    value = models.CharField(max_length=50)
    def __str__(self):
        return 'cctv_inside of {}'.format(self.gcg)
class Gcg(models.Model):
    gcg_id = models.IntegerField(unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='gcg_set', on_delete=models.PROTECT)
    # owner = models.ForeignKey('Owner', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    snode_num = models.IntegerField()
    anode_num = models.IntegerField()
    cctv_outside_num = models.IntegerField()
    cctv_inside_num = models.IntegerField()
    def __str__(self):
        return '[user : ({}) / gcg_id : ({})]'.format(self.user, self.gcg_id)
    pass
# 사실상 gcg 모델과 gcginfo모델을 합쳐도 상관없음
class GcgInfo(models.Model):
    gcg = models.OneToOneField('Gcg', on_delete=models.CASCADE)
    snode_num = models.IntegerField()
    data_period = models.DateTimeField()
    anode_num = models.IntegerField()
    cctv_num = models.IntegerField()
    ipv4 = models.CharField(max_length=100)
    ipv6 = models.CharField(max_length=100)
    version = models.CharField(max_length=50)
    mcu = models.CharField(max_length=50)   # choice
    os = models.CharField(max_length=50)    # choice
    updated_at = models.DateTimeField(auto_now=True)
    pass

class Snode(models.Model):
    gcg = models.ForeignKey('Gcg', on_delete=models.PROTECT)
    snode_id = models.IntegerField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    snode_value = models.IntegerField(default=None)
    def __str__(self):
        return 'Gcg : ({}) / Snode_id : ({})'.format(self.gcg, self.snode_id)
    pass

class Anode(models.Model):
    gcg = models.ForeignKey('Gcg', on_delete=models.PROTECT)
    anode_id = models.IntegerField(unique=True)
    anode_value = models.BooleanField(default=None)
    priority = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return 'Gcg : ({}) / Anode_id : ({})'.format(self.gcg, self.anode_id)
    pass

class SnodeInfo(models.Model):
    snode = models.OneToOneField('Snode', on_delete=models.CASCADE)
    sw_version = models.CharField(max_length=50)
    register_id = models.IntegerField()     # unique 물어보기
    register_date = models.DateTimeField(auto_now_add=True)
    node_status = models.CharField(max_length=50)
    monitor = models.CharField(max_length=50)   #choice
    set_vlaue = models.CharField(max_length=100, blank=True)
    comm_err_num = models.IntegerField()
    service_err_num = models.IntegerField()
    updated_at = models.DateTimeField(auto_now=True)

    pass

class AnodeInfo(models.Model):
    anode = models.OneToOneField('Anode', on_delete=models.CASCADE)
    sw_version = models.CharField(max_length=50)
    register_id = models.IntegerField()  # unique 물어보기
    register_date = models.DateTimeField(auto_now_add=True)
    node_status = models.CharField(max_length=50)
    opr_status = models.CharField(max_length=100)
    monitor = models.CharField(max_length=50)  # choice
    set_vlaue = models.CharField(max_length=100, blank=True)
    emergency_id = models.ForeignKey('Snode', on_delete=models.CASCADE)
    comm_err_num = models.IntegerField()
    service_err_num = models.IntegerField()
    updated_at = models.DateTimeField(auto_now=True)
    pass

class Address(models.Model):
    pass


class VegiType(models.Model):
    VEGI_TYPE = (
        ('a', '오이'),
        ('b', '딸기'),
        ('c', '더덕'),  # 이는 나중에 가나다 순으로 정렬하는게 가독성을 높일수 있을듯 ?
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='daily_set', on_delete=models.PROTECT)
    # owner = models.ForeignKey('Owner', on_delete=models.PROTECT) 아직 유저모델을 만들지 않아 보류
    vegi_type = models.CharField(max_length=1, choices=VEGI_TYPE)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.get_vegi_type_display()
    def get_absolute_url(self):
        return reverse('palm:vegi_category')

class Record(models.Model):
    VEGI_DATE = (
        ('s', '재배 시작'),  # start
        ('i', '재배중'),  # ing
        ('e', '재배 종료'),  # end
    )
    # owner = models.ForeignKey('Owner', on_delete=models.PROTECT) 아직 유저모델을 만들지 않아 보류
    vegi_type = models.ForeignKey(VegiType, on_delete=models.PROTECT)
    vegi_size = models.FloatField()
    vegi_condition = models.CharField(max_length=50)     # choice
    vegi_cultivation = models.CharField(max_length=1, choices=VEGI_DATE)      # choice
    vegi_shipment = models.FloatField()
    vegi_comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def get_absolute_url(self):
        return reverse('palm:record_detail', args=[self.vegi_type_id, self.id])

class Emergency(models.Model):
    gcg = models.ForeignKey('Gcg', on_delete=models.CASCADE)
    emergency_id = models.ForeignKey('Snode', on_delete=models.CASCADE)
    u_value = models.FloatField()
    r_value = models.FloatField()
    l_value = models.FloatField()
    anode = models.ForeignKey('Anode', on_delete= models.CASCADE)
    priority = models.IntegerField()
    # 나중에 우선순위에 gcg별로 우선순위를 부여하여야함
    updated_at = models.DateTimeField(auto_now = True)
    def __str__(self):
        return 'Emergency mode for Gcg : ({})'.format(self.gcg)
class Operating(models.Model):
    gcg = models.ForeignKey('Gcg', on_delete=models.CASCADE)
    opr_type = models.CharField(max_length=100)
    opr_comment = models.TextField()
    snode_num = models.IntegerField()
    anode_num = models.IntegerField()
    u_value = models.FloatField()
    r_value = models.FloatField()
    l_value = models.FloatField()
    updated_at = models.DateTimeField(auto_now = True)
    def __str__(self):
        return 'Operating Type : ({}) / gcg_id : ({})'.format(self.opr_type, self.gcg)
class OprSnode(models.Model):
    operating = models.ForeignKey('Operating', on_delete=models.CASCADE)
    snode = models.ForeignKey('Snode', on_delete=models.CASCADE)
    def __str__(self):
        return 'Operating Snode : ({}) / Snode : ({})'.format(self.operating, self.snode)
class OprAnode(models.Model):
    operating = models.ForeignKey('Operating', on_delete=models.CASCADE)
    anode = models.ForeignKey('Anode', on_delete= models.CASCADE)
    priority = models.IntegerField()
    def __str__(self):
        return 'id : ({}) / Operating Anode : ({}) . priority : ({})'.format(self.id, self.operating, self.priority)
class TestSnode(models.Model):
    gcg = models.ForeignKey('TestGcg', on_delete= models.CASCADE)
    snode_id = models.IntegerField()
    snode_value_temp = models.IntegerField(default=0, blank=True)
    snode_value_humd = models.IntegerField(default=0, blank=True)
    # value 테이블을 만들질 말지 생각 중간평가 이후
    house = models.ForeignKey('TestHouse', on_delete=models.CASCADE, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} / house : {} / snode_id : {}'.format(self.gcg, self.house, self.snode_id)
class TestAnode(models.Model):
    gcg = models.ForeignKey('TestGcg', on_delete=models.CASCADE)
    anode_id = models.IntegerField()
    anode_value = models.BooleanField(default=False)
    house = models.ForeignKey('TestHouse', on_delete=models.CASCADE, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '{} / house : {} / anode_id : {}'.format(self.gcg, self.house, self.anode_id)
class TestGcg(models.Model):
    gcg_id = models.IntegerField()
    def __str__(self):
        return 'Gcg_id : {}'.format(self.gcg_id)
class TestHouse(models.Model):
    gcg = models.ForeignKey('TestGcg', on_delete=models.CASCADE)
    def __str__(self):
        return '{} 동'.format(self.id)
class Test1(models.Model):
    first_name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
class TestN(models.Model):
    test1_id = models.ForeignKey('Test1', on_delete=models.CASCADE)
    last_name = models.CharField(max_length=50)

palm/forms.py
from django import forms
from .models import Record, VegiType, Emergency, Operating

class VegiTypeForm(forms.ModelForm):
    class Meta:
        model = VegiType
        fields = '__all__'

class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        exclude = ['vegi_type']
        # fields = '__all__'
        # 일단 온도 등에 관한 정보는 자동으로 입력될 정보로 표현됨
        # 즉 일단 온도등에 관한 정보는 숨겨둔다 그리고 위 주석과 같이 처리
class EmergencyForm(forms.ModelForm):
    class Meta:
        model = Emergency
        fields = '__all__'
class OperatingForm(forms.ModelForm):
    class Meta:
        model = Operating
        fields = '__all__'

palm/templates/record/layout.html
{% extends "layout.html" %}
{% block title %} 일지작성 {% endblock %}

palm/templates/record/record_detail.html
{% extends "record/layout.html" %}
{% block content %}
<div class = "container">
    <div class = "row">
        <div class = "col-sm-12">
            <h1>{{record.id}}</h1>
            <h1>{{record.vegi_type_id}}</h1>
            <h1>{{record.vegi_type}}</h1>
            <a href="{% url "palm:record_list" record.vegi_type_id %}" class = "btn btn-primary">Record List</a>
            <a href="{% url "palm:record_edit" record.vegi_type_id record.id %}" class = "btn btn-primary">Record Edit</a>
        </div>
    </div>
</div>
{% endblock %}

palm/templates/record/record_form.html
{% extends "record/layout.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" />
</form>
{% endblock %}

palm/templates/record/record_list.html
{% extends "record/layout.html" %}
{% block content %}
<div class ="row">
    <p class = "col-sm-12">
        <div class="alert alert-info">
        </div>
            <a href="{% url "palm:record_new" vegi_type_id %}" class = "btn btn-primary pull-right">New Record</a>
            <table class = "table table-hover table-bordered">

<!-- 여기서 데이터베이스 SQL 언어 발생-->
                <thead>
                    <tr>
                        <th>id</th>
                        <th>created at</th>
                        <th>updated at</th>
                    </tr>
                </thead>
                <tbody>
            {% for list in record_qurry %}
                    <tr>
                        <td>{{list.id}}</td>
                        <td><a href="{% url "palm:record_detail" vegi_type_id list.id %}">{{list.created_at}}</a></td>
                        <td>{{list.updated_at}}</td>
                    </tr>
                </tbody>
            {% endfor %}
            </table>
    </div>
{% endblock %}

palm/templates/record/test.html
{% extends "record/layout.html" %}

{% block chart %}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript">
    google.charts.load('current', {'packages':['line', 'corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart_TH);
    google.charts.setOnLoadCallback(drawChart_co2);
    function drawChart_TH() {

      var button = document.getElementById('change-chart');
      var chartDiv = document.getElementById('TH_chart_div');

      var data = new google.visualization.DataTable({{json_th|safe}});

      var TH_Options = {
        chart: {
          title: 'change temperature & humidity at time period'
        },
        width: 900,
        height: 500,
        series: {
          // Gives each series an axis name that matches the Y-axis below.
          0: {axis: 'Temps'},
          1: {axis: 'Humidity'}
        },
        axes: {
          // Adds labels to each axis; they don't have to match the axis names.
          y: {
            Temps: {label: 'temperature(C)'},
            Humidity: {label: 'Humidity(%)'}
          }
        }
      };


      var TH_Chart = new google.charts.Line(chartDiv);
      TH_Chart.draw(data, TH_Options);



    }


    function drawChart_co2() {
      var button = document.getElementById('change-chart');
      var chartDiv = document.getElementById('co2_chart_div');

      var data = new google.visualization.DataTable({{json_co2|safe}});

      var co2_Options = {
        chart: {
          title: 'change Co2 concentration at time period'
        },
        width: 900,
        height: 500,
      };


      var co2_Chart = new google.charts.Line(chartDiv);
      co2_Chart.draw(data, co2_Options);

    }
</script>
{% endblock %}

{% block content %}
    <!--Div that will hold the pie chart-->
<h1>Test Table created</h1>
<div id = "TH_chart_div"></div>
<h1> Table created using ToJSCode</h1>
<div id = "co2_chart_div"></div>
<h1>Table created using ToJSon</h1>
{{json_co2}}
<p>
{{jscode_co2}}
<hr>
{{json_th}}
<p>
{{jscode_th}}
{% endblock %}

palm/templates/record/vegi_category.html
{% extends "record/layout.html" %}
{% block content %}
<div class ="row">
    <p class = "col-sm-12">
        <div class="alert alert-info">
        </div>

    <a href="{% url "palm:record_vegi_new" %}" class = "btn btn-primary pull-right">New Vegetable Category</a>
    <p>
            <table class = "table table-hover table-bordered">

<!-- 여기서 데이터베이스 SQL 언어 발생-->
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>농장주</th>
                        <th>작물</th>
                        <th>생성날짜</th>
                        <th>재배 상황</th>
                        <th>재배 기간</th>
                        <th>일지 개수</th>
                    </tr>
                </thead>
                <tbody>
            {% for vegi_list in vegi_category %}
                    <tr>
                        <td>{{vegi_list.id}}</td>
                        <td>{{vegi_list.user}}</td>
                        <!-- vegi_type에서 링크를 걸어주어야함 -->
                        <td><a href="{% url "palm:record_list" vegi_list.id %}">{{vegi_list.get_vegi_type_display}}</a></td>
                        <td>{{vegi_list.created_at }}</td>
                        <td>{{vegi_list.record_set.all.last.get_vegi_cultivation_display}}</td>
                        <td>{{vegi_list.record_set.all.first.created_at}} ~ {{vegi_list.record_set.all.last.created_at}}</td>
                        <td>{{vegi_list.record_set.all.count}}</td>
                    </tr>
                </tbody>
{% endfor %}
            </table>
    </div>
{% endblock %}